# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - node -v
          - npm -v
          - git --version
          - npm cache clean --force
          - npm i
          - npm install -g @angular/cli
          - ng build --prod --build-optimizer --progress=false
          - cd dist/clientdemo
          - pipe: atlassian/aws-s3-deploy:0.4.4
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'ap-south-1'
              S3_BUCKET: 'mclientdemo'
              ACL: 'public-read'
              LOCAL_PATH: '$(pwd)'